FROM ubuntu

MAINTAINER Marc Brooks <acomfygeek@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -q

RUN apt-get install -y \
	texlive-base \
	texlive-bibtex-extra \
	texlive-fonts-recommended \
	texlive-fonts-extra \
	texlive-latex-base \
	texlive-latex-extra \
	texlive-latex-recommended \
	texlive-science

